services:
  game-archive:
    build: .
    container_name: game-archive
    restart: unless-stopped
    dns:
      - 192.168.20.1
      - 223.5.5.5
    extra_hosts:
      - "api.rawg.io:104.16.249.144"
    ports:
      - "8080:8000"
    environment:
    - SCAN_ENABLE=true
    - SCAN_CRON=0 3 * * *
    - SCAN_THROTTLE_MS=50
    - SCAN_WEEKLY_FULL_CHECK=false
    - RAWG_API_KEY=***REMOVED-RAWG-API-KEY***
    volumes:
      - /vol1/1000/docker/game-archive/data:/app/data
      - /vol02/1000-1-dd21201d/game_station:/vol/baidu

