<script setup>
import { computed, onMounted, onUnmounted, reactive, ref } from 'vue'

const games = ref([]), tasks = ref([]), error = ref(''), active = ref(null), showForm = ref(false), searchResults = ref([]), searching = ref(false), now = ref(Date.now()), scanStatus = ref({ status:'idle', next_run_at:null })
const refreshing = reactive({}), refreshCooldowns = reactive({}), refreshErrors = reactive({})
const filters = reactive({ q: '', source_type: '', play_status: '', sort: 'updated' })
const blank = () => ({ title:'', alias:'', cover_url:'', description:'', developer:'', publisher:'', release_date:null, rating:null, tags:'', series:'', source_type:'custom', source_id:'', resource_type:'none', resource_url:'', play_status:'favorite' })
const form = reactive(blank()), scrape = reactive({ q:'', source_type:'rawg' }), download = reactive({ download_url:'', target_path:'' })
const statuses = { favorite:'仅收藏', archived:'已归档', downloading:'下载中', completed:'已通关' }
const api = async (path, options={}) => { const r = await fetch(path, { headers:{'Content-Type':'application/json'}, ...options }); if (!r.ok) throw new Error((await r.json().catch(()=>({detail:r.statusText}))).detail); return r.status === 204 ? null : r.json() }
const cover = value => value || 'data:image/svg+xml,' + encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="400" height="560"><rect width="100%" height="100%" fill="#27303d"/><text x="50%" y="50%" fill="#94a3b8" text-anchor="middle" font-size="28">NO COVER</text></svg>')
async function load() { try { [games.value, tasks.value, scanStatus.value] = await Promise.all([api('/api/games?'+new URLSearchParams(filters)), api('/api/downloads'), api('/api/scans/status')]); error.value='' } catch(e) { error.value=e.message } }
function openNew() { Object.assign(form, blank()); active.value=null; searchResults.value=[]; showForm.value=true }
function openGame(game) { active.value=game; Object.assign(form, game); download.download_url=''; download.target_path=''; showForm.value=true }
async function save() { try { const url=active.value?`/api/games/${active.value.id}`:'/api/games'; await api(url,{method:active.value?'PUT':'POST',body:JSON.stringify(form)}); showForm.value=false; await load() } catch(e) { error.value=e.message } }
async function removeGame() { if (active.value && confirm('确认删除此游戏及其任务？')) { await api(`/api/games/${active.value.id}`,{method:'DELETE'}); showForm.value=false; await load() } }
async function scrapeSearch() { searching.value=true; try { searchResults.value=await api(`/api/metadata/search?${new URLSearchParams(scrape)}`) } catch(e) { error.value=e.message } finally { searching.value=false } }
function choose(item) { Object.assign(form, {...blank(), ...item, resource_type:'none', play_status:'favorite'}); searchResults.value=[] }
async function addDownload() { if (!active.value) return; try { await api('/api/downloads',{method:'POST',body:JSON.stringify({game_id:active.value.id,...download})}); download.download_url=''; download.target_path=''; await load() } catch(e) { error.value=e.message } }
async function uploadCover(event) { if (!active.value || !event.target.files[0]) return; const data=new FormData(); data.append('file',event.target.files[0]); const result=await fetch(`/api/games/${active.value.id}/cover`,{method:'POST',body:data}); if(!result.ok) error.value='封面上传失败'; else { Object.assign(form,await result.json()); await load() } }
const isRefreshCooling = game => (refreshCooldowns[game.id] || 0) > now.value
async function refreshMetadata(game) { if (refreshing[game.id] || isRefreshCooling(game)) return; refreshing[game.id]=true; delete refreshErrors[game.id]; try { await api(`/api/games/${game.id}/refresh-metadata`,{method:'POST'}); refreshCooldowns[game.id]=Date.now()+60000; await load(); setTimeout(load, 1000) } catch(e) { refreshErrors[game.id]=e.message; setTimeout(()=>delete refreshErrors[game.id],3000) } finally { refreshing[game.id]=false } }
const scanRunning = computed(() => ['pending','running'].includes(scanStatus.value.status))
const nextScanAt = computed(() => scanStatus.value.next_run_at ? new Date(scanStatus.value.next_run_at).toLocaleString() : '未计划')
async function triggerScan(full=false) { if (full && !confirm('确认重建全量索引？')) return; try { scanStatus.value=await api(`/api/scans/${full?'full':'incremental'}`,{method:'POST',body:full?JSON.stringify({confirm:true}):undefined}) } catch(e) { error.value=e.message } }
const visibleTasks = computed(() => active.value ? tasks.value.filter(t=>t.game_id===active.value.id) : [])
let timer; onMounted(()=>{load();timer=setInterval(()=>{now.value=Date.now();load()},3000)}); onUnmounted(()=>clearInterval(timer))
</script>

<template>
  <main class="mx-auto max-w-7xl p-4 md:p-8">
    <header class="mb-7 flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><h1 class="text-3xl font-bold tracking-tight">GAME ARCHIVE</h1><p class="mt-1 text-sm text-slate-400">你的个人游戏归档库</p></div><button class="btn" @click="openNew">+ 添加游戏</button></header>
    <p v-if="error" class="mb-4 rounded bg-red-950 p-3 text-red-200">{{ error }}</p>
    <section class="panel mb-6 grid gap-3 md:grid-cols-4"><input v-model="filters.q" @input="load" placeholder="搜索游戏名" /><select v-model="filters.source_type" @change="load"><option value="">所有类型</option><option value="rawg">PC / 主机游戏</option><option value="vndb">GAL / 视觉小说</option><option value="custom">自定义</option></select><select v-model="filters.play_status" @change="load"><option value="">所有状态</option><option v-for="(label,key) in statuses" :value="key">{{label}}</option></select><select v-model="filters.sort" @change="load"><option value="updated">最近更新</option><option value="created">最近添加</option><option value="rating">评分最高</option></select></section>
    <section v-if="games.length" class="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-5 xl:grid-cols-6"><article v-for="game in games" :key="game.id" class="group relative cursor-pointer overflow-hidden rounded-lg bg-panel shadow-lg" @click="openGame(game)"><button class="absolute right-2 top-2 z-10 flex h-8 w-8 items-center justify-center rounded-full bg-slate-950/80 p-0 text-slate-200 hover:bg-slate-700" :disabled="refreshing[game.id] || isRefreshCooling(game)" :title="isRefreshCooling(game) ? '元数据刷新冷却中' : '刷新元数据'" aria-label="刷新元数据" @click.stop="refreshMetadata(game)"><svg class="h-4 w-4" :class="{'animate-spin': refreshing[game.id]}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M20 11a8.1 8.1 0 0 0-15.5-2M4 5v4h4M4 13a8.1 8.1 0 0 0 15.5 2M20 19v-4h-4"/></svg></button><p v-if="refreshErrors[game.id]" class="absolute left-2 right-2 top-11 z-10 rounded bg-red-950/90 px-2 py-1 text-xs text-red-200">{{refreshErrors[game.id]}}</p><img :src="cover(game.cover_url)" class="aspect-[2/3] w-full object-cover transition duration-300 group-hover:scale-105" /><div class="p-3"><h2 class="truncate font-semibold">{{game.title}}</h2><div class="mt-2 flex justify-between text-xs text-slate-400"><span>{{ game.rating ? game.rating.toFixed(1) : '—' }}</span><span class="truncate pl-2">{{game.tags || statuses[game.play_status]}}</span></div></div></article></section>
    <p v-else class="py-20 text-center text-slate-500">还没有游戏，点击右上角开始归档。</p>

    <section class="panel mt-6"><div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="font-semibold">扫描配置</h2><p class="mt-1 text-sm text-slate-400">下次增量扫描：{{nextScanAt}}</p><p v-if="scanRunning" class="mt-1 text-sm text-accent">扫描中：{{scanStatus.message}}</p></div><div class="flex gap-2"><button class="btn-muted" :disabled="scanRunning" @click="triggerScan()">{{scanRunning?'扫描中':'立即增量扫描'}}</button><button class="btn" :disabled="scanRunning" @click="triggerScan(true)">重建全量索引</button></div></div></section>

    <div v-if="showForm" class="fixed inset-0 z-10 overflow-y-auto bg-black/70 p-4"><section class="mx-auto my-4 max-w-4xl rounded-xl bg-panel p-5 md:my-10"><div class="mb-5 flex items-center justify-between"><h2 class="text-xl font-bold">{{active ? active.title : '添加游戏'}}</h2><button class="btn-muted" @click="showForm=false">关闭</button></div>
      <div v-if="!active" class="mb-6 rounded-lg bg-slate-800 p-4"><h3 class="mb-3 font-semibold">自动刮削元数据</h3><div class="flex gap-2"><input v-model="scrape.q" @keyup.enter="scrapeSearch" placeholder="输入游戏名"/><select v-model="scrape.source_type" class="max-w-32"><option value="rawg">RAWG</option><option value="vndb">VNDB</option></select><button class="btn" :disabled="searching" @click="scrapeSearch">{{searching?'搜索中':'搜索'}}</button></div><div v-if="searchResults.length" class="mt-3 max-h-60 overflow-auto"><button v-for="item in searchResults" :key="item.source_id" class="block w-full border-b border-slate-700 text-left hover:bg-slate-700" @click="choose(item)">{{item.title}} <span class="text-slate-400">{{item.release_date || ''}}</span></button></div></div>
      <form class="grid gap-3 md:grid-cols-2" @submit.prevent="save"><label v-if="active">数据源<input :value="form.source_type.toUpperCase()" readonly></label><label>游戏名<input v-model="form.title" required></label><label>别名<input v-model="form.alias"></label><label>开发商<input v-model="form.developer"></label><label>发行商<input v-model="form.publisher"></label><label>发售日期<input v-model="form.release_date" type="date"></label><label>评分（0-100）<input v-model.number="form.rating" type="number" min="0" max="100"></label><label>标签（逗号分隔）<input v-model="form.tags"></label><label>系列<input v-model="form.series"></label><label>资源类型<select v-model="form.resource_type"><option value="none">无</option><option value="cloud_link">云盘链接</option><option value="nas_path">NAS 本地路径</option></select></label><label>资源链接 / 路径<input v-model="form.resource_url" placeholder="/vol/baidu/... 或 https://..."></label><label>游玩状态<select v-model="form.play_status"><option v-for="(label,key) in statuses" :value="key">{{label}}</option></select></label><label>封面 URL<input v-model="form.cover_url"></label><label class="md:col-span-2">简介<textarea v-model="form.description" rows="4"></textarea></label><div class="flex gap-2 md:col-span-2"><button class="btn" type="submit">保存</button><button v-if="active" class="bg-red-700" type="button" @click="removeGame">删除</button></div></form>
      <section v-if="active" class="mt-7 border-t border-slate-700 pt-5"><a v-if="form.resource_type !== 'none' && form.resource_url" class="btn mb-4 inline-block" :href="`/api/games/${active.id}/resource`" target="_blank">打开资源</a><h3 class="mb-3 font-semibold">自定义封面</h3><input type="file" accept="image/*" @change="uploadCover"><h3 class="mb-3 mt-5 font-semibold">下载到 NAS</h3><div class="grid gap-2 md:grid-cols-[1fr_1fr_auto]"><input v-model="download.download_url" placeholder="下载直链"><input v-model="download.target_path" placeholder="容器内绝对路径，如 /vol/baidu/游戏/x.7z"><button class="btn" :disabled="!download.download_url || !download.target_path" @click="addDownload">开始下载</button></div><div v-for="task in visibleTasks" :key="task.id" class="mt-3 rounded bg-slate-800 p-3 text-sm"><div class="flex justify-between"><span>{{task.status}}</span><span>{{task.file_size ? Math.round(task.downloaded/task.file_size*100)+'%' : task.downloaded+' bytes'}}</span></div><div class="mt-2 h-1 overflow-hidden rounded bg-slate-700"><div class="h-full bg-accent" :style="{width: task.file_size ? (task.downloaded/task.file_size*100)+'%' : '0%'}"></div></div><p v-if="task.error_msg" class="mt-1 text-red-300">{{task.error_msg}}</p></div></section>
    </section></div>
  </main>
</template>